language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install coverage coveralls
- python bootstrap.py
- "./bin/buildout"
script:
- coverage erase
- coverage run ./bin/test
- coveralls
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password:
    secure: n8CKQW2ugR7jSfziMchne037T80qo/cxhQ7mNFMyKOQXvaXBjlSzwOGUfNbw53txqtAtpCQhsHALggvqCtN/5vLxz4xfZ9xP+sRzpB6STueEPR+oPOrzPBjb9c+PDuvscQq4d1Cu+SR5GAPX18jnCZflAcRav5tXXJ7bIdY4ei5nEFn/Su6qNwjnHorMIUGCMtvWvdE4NuRv44p9oQMBbbQr7GTKCDSYbgO7OjRJJyzGtWXESdtG+v8m7OdkUFDiSwWEcJqY98748jbZF9OYr+gFOCq5zPxYjxzb8Tly7Eg5D/xrXb5TfXMq+xO0FJoZ40QpXDxo60tmAvKWuy0Syfvgna/wl/6meMS7/xCTfwwW1WfqSRpyfuyZwVhaE55DrteLQdlygvPeUjXCxBY5lgwL+j/OpDucueH/lF5+ogFs+T+ddXyJmzT2OHtYmfuQHQ7IeaE50PpqhdgY66y0N8yPwv1djUryKPA4I6VVeUoCL85+R8rTn6J4AB++zGsQgBQargbJZ5kp37rnB3lO8vK7x3BJ/28iXhxa8hohEtUx60E6Ie7HFLIrYwT/tRAoL5OHQa4aMa+tgxm3hHpfLpNUvlKAzkPWHVdrA3qyz3XnsCdtAZ1/yWTJR9SgSIT/IxCMtSDKVNxvdRCWY13/zrajIy83tCAvP0A4ATnDWIE=
  distributions: sdist bdist_egg bdist_wheel
  skip_existing: true
